### ISSUE TITLE
Big nesting in code

### ISSUE THREAD

**Issue by maddenbrain** [polyak01/ToDoList#2]
In DoneTaskAdaptor you setting listener in listener... For listening while you listening?
Bad code style. You must rework it.
str 92; str 107

Bad way is to create new listener every time you clicking the button.

**Comment by maddenbrain** [comment]
CurrentTasksAdapter str 115; str 129 - same

**Comment by polyak01** [comment]
There goes the animation when you click on the circle. It can not be realized in other ways.

**Comment by maddenbrain** [comment]
Just create builder for animation listener. Like:
AnimationListener getAnimListener() {
    new AnimationListener()...
}

**Comment by maddenbrain** [comment]
TaskFragment:60
replace 
if (item.isTask()) {
    //do job
}

with

if (!item.isTask())
    return;

//do job

**Comment by polyak01** [comment]
done
